#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the turtlebot3 usb connection."
echo ""

sudo cp `ros2 pkg prefix yeyu_bringup`/share/yeyu_bringup/script/99-turtlebot3-cdc.rules /etc/udev/rules.d/
echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
